/* #undef SDL_VENDOR_INFO */
#define SDL_REVISION_NUMBER 0

#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-2.31.0-gaf94954 (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-2.31.0-gaf94954"
#endif
